# Generated by Django 3.2.9 on 2022-02-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creationTime',
            new_name='creationDate',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
    ]
