# Generated by Django 3.2.9 on 2022-02-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220210_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=16)),
                ('deadline', models.DateField()),
                ('creationDate', models.DateField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project')),
            ],
        ),
    ]
